write: 
	gcc -c write_lel.c
	gcc -o write write_lel.o
read:
	gcc -c read_lel.c
	gcc -o read read_lel.o
operation:	
	gcc -c song_operation.c
	gcc -o song_op song_operation.o
	
clean:
	rm -rf *.o write read song_op *.bin
